safe:        false
auto:        false
server:      false
server_port: 4000
baseurl:    /
url: http://localhost:4000

source:      .
destination: ./_site
plugins:     ./_plugins

future:      false
lsi:         false
pygments:    false
markdown:    maruku
permalink:   none


title:  Beer Slayers
domain: beerslayers.com

